namespace GagspeakAPI.Enums;
public enum GagLayer
{
    UnderLayer = 0,
    MiddleLayer = 1,
    TopLayer = 2,
}

public static class GagEx
{
    public static int ToIndex(this GagLayer layer) => (int)layer;
}

public enum GagType
{
    None,
    BallGag,
    BallGagMask,
    BambooGag,
    BeltStrapGag,
    BitGag,
    BitGagPadded,
    BoneGag,
    BoneGagXL,
    CandleGag,
    CageMuzzle,
    CleaveGag,
    ChloroformGag,
    ChopStickGag,
    ClothWrapGag,
    ClothStuffingGag,
    CropGag,
    CupHolderGag,
    DeepthroatPenisGag,
    DentalGag,
    DildoGag,
    DuctTapeGag,
    DusterGag,
    FunnelGag,
    FuturisticHarnessBallGag,
    FuturisticHarnessPanelGag,
    GasMask,
    HarnessBallGag,
    HarnessBallGagXL,
    HarnessPanelGag,
    HookGagMask,
    InflatableHood,
    LargeDildoGag,
    LatexHood,
    LatexBallMuzzleGag,
    LatexPostureCollarGag,
    LeatherCorsetCollarGag,
    LeatherHood,
    LipGag,
    MedicalMask,
    MuzzleGag,
    PantyStuffingGag,
    PlasticWrapGag,
    PlugGag,
    PonyGag,
    PumpGaglv1,
    PumpGaglv2,
    PumpGaglv3,
    PumpGaglv4,
    RibbonGag,
    RingGag,
    RopeGag,
    ScarfGag,
    SensoryDeprivationHood,
    SockStuffingGag,
    SpiderGag,
    TentacleGag,
    WebGag,
    WhiffleGag,
}
